### ISSUE TITLE
Reduce the length of message

### ISSUE THREAD

**Issue by knight42** [knight42/kopilot#11]
I encountered an error today:
```
Error: create completion: error, This model's maximum context length is 4097 tokens. However, your messages resulted in 5515 tokens. Please reduce the length of the messages.
```

I can think of 2 options to solve it:
1. truncate the message to maxium length
2. prune the object, like only send the `status` field and related events

**Comment by pacoxu** [comment]
There are some defaulting filed that can be omitted, such as terminationGracePeriodSeconds. We may need to check the yaml.

- for pods,  ss I know the kubectl-apply annotation is very big. 
- for nodes, the `status.image` is large but useless.

**Comment by knight42** [comment]
@pacoxu Hi, I have filed #12 to remove `node.status.image`, `metadata.{labels,annotations}` from the object before submiting it to gpt api.
