### ISSUE TITLE
get object: no Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by kfirfer** [knight42/kopilot#14]
Hello

using OIDC to connect to the cluster and getting this error:

```
$ kubectl kopilot diagnose pod <pod>
Error: marshal object: get object: no Auth Provider found for name "oidc"
```

**Comment by knight42** [comment]
@kfirfer Hi, it seems the `kopilot` uploaded to `krew` has been outdated, I will make a new release ASAP.

**Comment by kfirfer** [comment]
@knight42 thanks!

**Comment by knight42** [comment]
@kfirfer Hi, I have release version 0.0.3. Please upgrade kopilot by running `kubectl krew upgrade kopilot` and see if this issue is resolved.

**Comment by kfirfer** [comment]
yes it is resolved, thanks!

**Comment by knight42** [comment]
Glad to hear that!
