### ISSUE TITLE
也有ai在里头吗

### ISSUE THREAD

**Issue by buffalo1024** [knight42/kopilot#2]
这名字，跟copilot有关系吗（好奇）。

**Comment by buffalo1024** [comment]
![image](https://user-images.githubusercontent.com/49835372/227092667-82dc50be-0b18-4829-b667-0d843a235138.png)
看漏了，的确有ai。太强了。

**Comment by knight42** [comment]
嗯现在这个项目使用了 chatgpt。
我先把这个 issue 关了，如果有其他建议欢迎创建别的 issue 讨论。
