### ISSUE TITLE
Feature Request: promote kopilot to a validating webhook which as a validation webhook 

### ISSUE THREAD

**Issue by mlycore** [knight42/kopilot#5]
LIke the title said, maybe kopilot could be deployed as a validating webhook, any kubernetes resources, like CRDs, submitted will need to be validated, reviewed or audited.

**Comment by knight42** [comment]
This might be a good idea, but I suspect  neither ChatGPT nor any other AI services are mature enough. I think product like [Open Policy Agent](https://www.openpolicyagent.org/) is a better choice in this case.

**Comment by mlycore** [comment]
Sure. It's good enought to be a kubectl plugin now.
