### ISSUE TITLE
output of `describe` includes events and is more readable

### ISSUE THREAD

**Issue by pacoxu** [knight42/kopilot#6]
https://github.com/knight42/kopilot/blob/4ede54e9becbf47972eff6b46bdd6fc5ed08930a/diagnose.go#L56
I just think that `kubectl describe` may be better here. However, it will use `kubectl`.

**Comment by knight42** [comment]
Thanks for your advice! Actually inculding related events is already on my TODO list. 

Regarding to switch to the output of `kubectl describe`, I am worried some internal details might be hidden hence the AI could not see the full picture and fails to make a precise diagnosis, so I might want to stick to the yaml format of the object.

**Comment by knight42** [comment]
This issue should be addressed by #16. Please upgrade to 0.0.3(`kubectl krew upgrade kopilot`) and feel free to give it a try.
